version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: achraf123
      MYSQL_USER: achraf
      MYSQL_PASSWORD: achraf123
      MYSQL_DATABASE: shopdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
